### ISSUE TITLE
Convert Linerenderer to Mesh

### ISSUE THREAD

**Issue by hao-l1** [dilmerv/VRDraw#1]
Hi, @dilmerv. I've downloaded the previous version of VRDraw, the one with splinemesh cuz I want the lines I have drawn to be mesh so that I can export them as .obj file. I'm quite struggling with this issue. When I run the play mode and start drawing, it becomes very slow and fps is very low. The splines were not generated in the way as I have expected. Do you know what is happening? Or is there any other way I can have convert linerenderer to mesh? Thank you!

**Comment by dilmerv** [comment]
The reason I removed the spline implementation is because it was way too slow, there is a method in the LineRender itself to convert it to a mesh, I still think it may be very slow but you can try it [here](https://docs.unity3d.com/ScriptReference/LineRenderer.BakeMesh.html)
